apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhopp-go-azure 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=rhopp-go-azure
    backstage.io/kubernetes-id: rhopp-go-azure 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: rhopp-rhtap-testing/rhopp-go-azure
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: rhopp-rhtap-testing.rhopp-go-azure
    nexus-repository-manager/docker.image-name: rhtap/rhopp-go-azure
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 